import React from "react";

import { useRouter } from "expo-router";
import { View, Text, StyleSheet, Pressable } from "react-native";

import EvilIcons from "@expo/vector-icons/EvilIcons";


const Instructions = (): JSX.Element => {
  const router = useRouter();

  const handleClose = () => {
    router.back();
  };

  return (
    <View style={styles.container}>
      <View style={styles.headingContainer}>
        <Pressable onPress={handleClose}>
          <EvilIcons name="close" size={32} color="white" />
        </Pressable>
        <Text style={styles.headingText}>Instructions</Text>
        <View style={{ width: 32, height: 32 }} />
      </View>

      <View style={styles.mainContainer}>
        <View style={styles.blurBackground} />
        <View style={styles.textContainer}>
          <Text style={{ zIndex: 20, color: "white", textAlign: "center", fontSize: 15, fontFamily: "TitilliumWeb-Regular" }}>
            One dead is a strategic guessing game. The goal of the game to correctly guess a four digit number generated by computer with least amount of tries and in the least amount of time
          </Text>

          <Text style={{ zIndex: 20, color: "white", textAlign: "center", fontSize: 15, fontFamily: "TitilliumWeb-Regular" }}>
            For every trial that you make you are given two clues, dead and injured. Dead count is the number of digits that you guessed correctly and are in the correct position. Injured count is the number of digits that you guessed correctly but are in the wrong position.
          </Text>

          <Text style={{ zIndex: 20, color: "white", textAlign: "center", fontSize: 15, fontFamily: "TitilliumWeb-Regular" }}>
            For example, if the number is 1234 and you guessed 1356, you will get 1 dead and 1 injured. Since the dead number would be 1 and the injured number would be 3. The dead digit is 1 because 1 is in the correct position. The injured digit is 3 because 3 is in the wrong position.
          </Text>
        </View>
      </View>
    </View>
  );
};


export default Instructions;

const styles = StyleSheet.create({
  container: {
    gap: 48,
    flex: 1,
    padding: 24,
    width: "100%",
    height: "100%",
    justifyContent: "space-between",
  },
  headingText: {
    color: "white",
    fontSize: 24,
    fontFamily: "TitilliumWeb-Regular",
  },
  blurBackground: {
    top: 0,
    left: 0,
    zIndex: 10,
    width: "100%",
    height: "100%",
    position: "absolute",
    backgroundColor: "rgba(255, 255, 255, 0.2)",
  },
  textContainer: {
    gap: 14,
    zIndex: 20,
    padding: 8,
    width: "100%",
    height: "100%",
    position: "absolute",
    alignItems: "center",
    justifyContent: "center",
  },
  mainContainer: {
    flex: 1,
    gap: 24,
    width: "100%",
    height: "50%",
    borderWidth: 2,
    borderColor: "white",
    position: "relative",
    justifyContent: "center",
  },
  headingContainer: {
    height: 50,
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
});