# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Dev Deployment
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "yarn"

      - name: Install dependencies
        run : yarn install

      - name: Setup secrets
        run: echo "$DEPLOY_SECRETS" > .env
        env:
          DEPLOY_SECRETS: ${{ secrets.DEPLOY_SECRETS }}
      
      - name: Build web app
        run: |
          for i in $(cat .env); do export "$i"; done
          yarn build:web
      
      - name: Deploy web
        run: |
          for i in $(cat .env); do export "$i"; done
          yarn deploy:web

  run_migrations:
    needs: deploy
    name: Run migrations
    runs-on: ubuntu-latest
    concurrency: migration-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "yarn"

      - name: Setup secrets
        run: echo "$DEPLOY_SECRETS" > .env
        env:
          DEPLOY_SECRETS: ${{ secrets.DEPLOY_SECRETS }}

      - name: Install dependencies
        run : yarn install --production=false

      - run: yarn db:migrate
